version: '3.9'

services:
    rickandmorty-api:
        image: 'rickandmorty-api:latest'
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rickandmorty-api
        ports:
          - 8080:8080
        restart: always
        networks:
          - spring-cloud-network

networks:
    spring-cloud-network:
        driver: bridge